# One of [trace, debug, info, warn, error]
[log]
level="info"

[sync]
enabled=true
check_interval_mins=5

[database]
file='modulate.db'

[web]
host="0.0.0.0"
port=4000
public_url="http://127.0.0.1:4000"
jwt_secret="something_random"

# Spotify API credentials (https://developers.spotify.com/dashboard)
# Be sure to set the redirect URI in your developer app to "{WEB_PUBLIC_URL}/callback" (e.g. "http://127.0.0.1:4000/callback")
[spotify]
client_id=""
client_secret=""

# Sentry DSN (leave blank to disable)
[sentry]
dsn=""
