# one of [trace, debug, info, warn, error]
log_level = "info"

[web]
host = "0.0.0.0"
port = 4000
allowed_origins = ["", "http://localhost:4000"]

[spotify]
client_id = "change_me"
client_secret = "change_me"
callback_uri = "http://localhost:4000/callback"
